In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import numpy as np
import pandas as pd
ship_fire = pd.read_csv('/content/drive/MyDrive/deu2/4월_프로젝트/Machine_dataset/all_ship_fire_data.csv', encoding = 'cp949')

In [ ]:
ship_fire

In [ ]:
import pandas as pd

# 위도 컬럼 선택 후 도, 분, 초 분리
latitudes = ship_fire['위도'].str.split('|', expand=True).astype(float)


# for문을 사용하여 모든 위도 값들에 적용
for i in range(len(ship_fire['위도'])):
    lat = latitudes.iloc[i]
    lat_minute = (lat[1] + lat[2] / 60) / 60
    lat_degree = lat[0] + lat_minute
    ship_fire['위도'][i] = lat_degree

# 결과 확인
ship_fire

<ipython-input-37-259a6874a9f7>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ship_fire['위도'][i] = lat_degree

,발생일시,발생해역,발생유형,발생원인,기상특보,위도,경도,선종,톤수
0,2011-12-31 13:20,영해-EEZ,화재,관리소홀,양호,35.316667,129|51|00,어선,9.77
1,2011-12-30 21:15,항계내,화재,정비불량,양호,35.071667,129|00|70,어선,2194.00
2,2011-12-28 16:00,영해,화재,화기취급부주의,양호,34.483333,126|06|00,어선,29.00
3,2011-12-20 17:08,영해-EEZ,화재,정비불량,양호,36.3,130|01|00,어선,48.00
4,2011-12-20 05:27,영해,화재,기타,양호,37.533333,129|21|00,어선,7.93
...,...,...,...,...,...,...,...,...,...
1207,2021-01-12 05:36,영해,화재,원인미상,양호,34.108889,127 | 55 | 50,어선,9.77
1208,2021-01-08 10:35,협수로,화재,화기취급부주의,양호,34.563333,128 | 4 | 33,어선,4.01
1209,2021-01-08 10:05,항계 내,화재,화기취급부주의,양호,35.936944,126 | 31 | 54,어선,9.77
1210,2021-01-05 17:08,항계 내,화재,원인미상,양호,33.517778,126 | 31 | 55,어선,5.77
1211,2021-01-02 00:23,항계 내,화재,화기취급부주의,양호,34.726944,127 | 33 | 38,어선,9.77

In [ ]:
import pandas as pd

# 위도 컬럼 선택 후 도, 분, 초 분리
latitudes = ship_fire['경도'].str.split('|', expand=True).astype(float)


# for문을 사용하여 모든 위도 값들에 적용
for i in range(len(ship_fire['경도'])):
    lat = latitudes.iloc[i]
    lat_minute = (lat[1] + lat[2] / 60) / 60
    lat_degree = lat[0] + lat_minute
    ship_fire['경도'][i] = lat_degree

# 결과 확인
ship_fire

<ipython-input-38-1c4d23e61840>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ship_fire['경도'][i] = lat_degree

,발생일시,발생해역,발생유형,발생원인,기상특보,위도,경도,선종,톤수
0,2011-12-31 13:20,영해-EEZ,화재,관리소홀,양호,35.316667,129.85,어선,9.77
1,2011-12-30 21:15,항계내,화재,정비불량,양호,35.071667,129.019444,어선,2194.00
2,2011-12-28 16:00,영해,화재,화기취급부주의,양호,34.483333,126.1,어선,29.00
3,2011-12-20 17:08,영해-EEZ,화재,정비불량,양호,36.3,130.016667,어선,48.00
4,2011-12-20 05:27,영해,화재,기타,양호,37.533333,129.35,어선,7.93
...,...,...,...,...,...,...,...,...,...
1207,2021-01-12 05:36,영해,화재,원인미상,양호,34.108889,127.930556,어선,9.77
1208,2021-01-08 10:35,협수로,화재,화기취급부주의,양호,34.563333,128.075833,어선,4.01
1209,2021-01-08 10:05,항계 내,화재,화기취급부주의,양호,35.936944,126.531667,어선,9.77
1210,2021-01-05 17:08,항계 내,화재,원인미상,양호,33.517778,126.531944,어선,5.77
1211,2021-01-02 00:23,항계 내,화재,화기취급부주의,양호,34.726944,127.560556,어선,9.77

In [ ]:
ship_fire.to_csv('ship_fire_data.csv', index=False, encoding = 'cp949')